### ISSUE TITLE
PO3 

### ISSUE THREAD

**Issue by PoisonVirus** [Cazadorsniper/PO3#688] opened 2019-10-31 19:27 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*3.1.44*
**Pack Mode:*Normal*
**Singleplayer, Multiplayer, or LAN?:*SinglePlayer*

**Description:*After u use the Wireless terminal u get a crash *

**Steps to reproduce:*use the wireless terminal couple of time in a different dimension*

**Crash log (use pastebin or issue will be closed):*https://pastebin.com/TEgC9XhA
[crash-2019-10-31_15.09.09-client.txt](https://github.com/Cazadorsniper/PO3/files/3795489/crash-2019-10-31_15.09.09-client.txt)
*

**Comment by Cazadorsniper** [comment] 2019-10-31 20:29
Duplicate of #687

**Closed by Cazadorsniper** 2019-10-31 20:29 UTC
Labels: duplicate
