### ISSUE TITLE
Extra planets crash while initializing phase 2

### ISSUE THREAD

**Issue by WeebsGames** [Cazadorsniper/PO3#1711] opened 2022-11-08 07:22 UTC
# Use the search function before reporting to see if the issue has been reported before.
3.4.10
Normal
Multiplayer

Game will not load past initializing phase 2 mods when trying to load extra planets. The error log says something about planet id -13 and having double space stations.

Launch Game to reproduce

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/Gt2u20yZ

**Comment by Cazadorsniper** [comment] 2022-11-08 12:51
Duplicate of #1709

**Closed as completed by Cazadorsniper** 2022-11-08 12:51 UTC
