### ISSUE TITLE
Neutral steel of the fifth degree requires 5 neutral steel of the fourth degree

### ISSUE THREAD

**Issue by RagingStormMC** [Cazadorsniper/PO3#1200] opened 2020-05-24 08:55 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.58A
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Not sure if it's a bug, but the recipe for neutral steel of the fifth degree has been changed, and the vivid alloy and tungsten ingots have been replaced with ns of the fourth degree. This seems like a bug because all of them use 3 of the previous kind of steel.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by LateNightTic** [comment] 2020-05-24 12:26
A workaround until this is either confirmed as intended or fixed by a release can be done

In /scripts/add_modes/all_enderio.zs
Replace:
mods.enderio.AlloySmelter.addRecipe(<contenttweaker:neutral_steel_5>, [<contenttweaker:neutral_steel_4>, <contenttweaker:neutral_steel_4> * 3, <contenttweaker:neutral_steel_4>], 20000, 1);

With:
mods.enderio.AlloySmelter.addRecipe(<contenttweaker:neutral_steel_5>, [<ore:ingotVividAlloy>, <contenttweaker:neutral_steel_4> * 3, <ore:ingotTungsten>], 20000, 1);

this would need to be done on all clients and the server if running MP.

**Comment by Cazadorsniper** [comment] 2020-05-24 12:52
Not intended but its the only solution because the alloy smelter recipe before was slightly broken.

**Comment by tjdalton** [comment] 2020-05-25 01:19
Just on this, the alloy smelter actually processes the recipe with 3 ingots, one in each slot, even though JEI says it should be 1-3-1.

This also breaks autocrafting with AE2, as it shoves all ingots into slot 1, so the craft never completes unless the ingots are moved manually.

**Comment by Cazadorsniper** [comment] 2020-05-28 15:55
Will have to add this recipe to the XML file and remove the script for it.

**Closed** 2020-05-29 00:55 UTC
Labels: Fixed For Next Update
