### ISSUE TITLE
Game crash + crash repport

### ISSUE THREAD

**Issue by Bajal45** [Cazadorsniper/PO3#553] opened 2019-08-14 08:29 UTC
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.0.41
singleplayer

Description: crash

Steps to reproduce : Play

Crash log : https://pastebin.com/n2iQptJJ

**Comment by Cazadorsniper** [comment] 2019-08-14 10:40
Duplicate of #469

**Closed by Cazadorsniper** 2019-08-14 10:40 UTC
