### ISSUE TITLE
Crashes all the time with no reason

### ISSUE THREAD

**Issue by MekaSenpai** [Cazadorsniper/PO3#519] opened 2019-07-27 10:14 UTC
I usually open the modpack and start playing, but at 5-15 minutes the game freezes and then i watch the game log (yeah, i have it open with the game) and it says my server is disconnecting and closing, i dont know what cause this but here is the crashlog:
https://pastebin.com/2BdRpHR4

**Comment by Cazadorsniper** [comment] 2019-07-27 13:45
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-27 13:45 UTC
Labels: Issue template Missing
