### ISSUE TITLE
Error starting server 3.1.56 - slimeknights/tconstruct - EventBus$1

### ISSUE THREAD

**Issue by rioricorick** [Cazadorsniper/PO3#1071] opened 2020-05-03 19:48 UTC
During server startup, errors like this repeat ~100 times then startup sits at a ">" prompt with no further action.

[12:40:31] [Server thread/ERROR] [FML]: Index: 373 Listeners:
[12:40:31] [Server thread/ERROR] [FML]: 0: HIGHEST
[12:40:31] [Server thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@da53f8c
[12:40:31] [Server thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@18db3635
[12:40:31] [Server thread/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@74232b2e
[12:40:31] [Server thread/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@1896039

It starts off with this:
-----------------------
[12:40:31] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@194844ee:
java.lang.NoClassDefFoundError: **slimeknights/tconstruct**/common/ModelRegisterUtil
        at com.mrthomas20121.tinkers_reforged.proxy.CommonProxy.registerToolModel(CommonProxy.java:42) ~[CommonProxy.class:?]
        at com.mrthomas20121.tinkers_reforged.Module.ModuleTools.registerItems(ModuleTools.java:103) ~[ModuleTools.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_878_ModuleTools_registerItems_Register.invoke(.dynamic) ~[?:?]

**Comment by Cazadorsniper** [comment] 2020-05-03 20:24
Duplicate of #1055

**Closed by Cazadorsniper** 2020-05-03 20:24 UTC
