### ISSUE TITLE
Arcane Construct - Empty bucket stays in input slot

### ISSUE THREAD

**Issue by Chili1998** [Cazadorsniper/PO3#917] opened 2020-03-20 14:21 UTC
Pack Version: 3.2.52
Pack Mode: Kappa
Singleplayer
Description: Damp Crystal recipe in arcane construct leaves empty buckets in item input block. Empty buckets can't get extracted and need to be removed manually. Maybe just use the water bucket in the crafting recipe and don't give the empty bucket back.

**Comment by Cazadorsniper** [comment] 2020-03-20 17:00
Duplicate of #877

**Closed by Cazadorsniper** 2020-03-20 17:00 UTC
Labels: duplicate
