### ISSUE TITLE
v3.3.56 server not starting

### ISSUE THREAD

**Issue by Kevitto** [Cazadorsniper/PO3#1072] opened 2020-05-03 21:39 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.56
**Pack Mode (Normal, Titan, Kappa): Normal
**Singleplayer, Multiplayer, or LAN?: Server

**Description: Server crashes on initial bootup (fresh installation)

**Steps to reproduce: Downloaded and installed server pack 3.3.56 from CurseForge, extracted, crashes.

**Crash log (use pastebin or issue will be closed): https://pastebin.com/Gxj6kEEU

**Comment by gatanes** [comment] 2020-05-03 21:48
Same crash log for me too

**Comment by gatanes** [comment] 2020-05-03 22:00
disable Tinkers' Reforged.

**Comment by Cazadorsniper** [comment] 2020-05-03 22:19
Duplicate of #1055

**Closed by Cazadorsniper** 2020-05-03 22:19 UTC
