### ISSUE TITLE
Does not load/takes near on an hour

### ISSUE THREAD

**Issue by Jordaan128** [Cazadorsniper/PO3#88] opened 2019-03-04 18:21 UTC
Hello,

I installed this pack a few days ago in hopes of playing it straight away however, the pack loads for about 40 minutes then crashes which I know is not right. Things like stitching textures and model loading takes an age. It is not my PC as I have 16GB ram 8 allocated, a ryzen 5 2600 and a 1070ti, I don't have any issues loading any other packs (that I'm aware off) any help or ideas would be appreciated as this seems like a really fun modpack. Thanks

**Comment by Zapstur** [comment] 2019-03-04 18:47
Ok, what type of RAM do you have?  DDR3?  DDR4?  And what is the speed of the drive you are running Twitch on?  And how much free space is left on that drive?  And, of course, the million dollar question: Are all important programs up to date (I.E. Drivers, Java)?

Asking because I have a laptop with far worse specs than you listed, and it loads up to the main menu in just under 10 minutes.  If those specs I asked for are all good, then that means there is something wrong on your system, and we can't help you with that, you'll have to get it looked at by a professional.

**Comment by Zapstur** [comment] 2019-03-04 18:53
Another important thing:  That drive might be badly fragmented (1% or less fragmentation is best, of course, even getting up to 4% causes major problems with a lot of programs), luckily there are good, free tools for that.  Personally, I recommend IOBit's "Smart Defrag" program because it is easy to understand, fast, and gets the job done EXTREMELY well.

**Comment by Jordaan128** [comment] 2019-03-04 18:53
DDR4 3200mhz, on a m.2 with 65gb free, and I've updated all drivers, I'll have a look at the defrag

**Comment by Jordaan128** [comment] 2019-03-04 18:57
Was defragged 8 days ago,

**Comment by Zapstur** [comment] 2019-03-04 18:57
Mind analyzing it and seeing what percentage it is at right now?

**Comment by Jordaan128** [comment] 2019-03-04 18:58
sure, one minute

**Comment by Jordaan128** [comment] 2019-03-04 19:03
Can't anaylze cause I have an SSD. didn't know that

**Comment by Zapstur** [comment] 2019-03-04 19:15
Seems weird that it was defragged 8 days ago, if it can't be scanned.   That said, since almost all the tech issues I can think of have been ruled out, there really isn't much else I can do to try to help.  If the system runs fine normally, then it probably isn't an issue with the BIOS either.  So, the only thing left I can think of, is that there might be a compatibility issue between the Forge version and your hardware.  That is VERY likely, since you said you can load up other modpacks just fine.

**Comment by Jordaan128** [comment] 2019-03-04 19:17
Yeah ikr, I was thinking of updating the bios but since other modpacks/games run fun I doubt thatd fix it, I do appreciate your suggestions though, thank you

**Comment by Saereth** [comment] 2019-03-05 15:19
we had several people run into this issue on our server, removing the waiting mod fixed it for all of us.

**Comment by Zapstur** [comment] 2019-03-05 16:15
The one that creates Pong?  Huh.  I guess it is possible that its code just isn't compatible with some systems...

**Comment by Jordaan128** [comment] 2019-03-05 21:03
What mod would that be?

**Comment by Zapstur** [comment] 2019-03-06 03:42
> What mod would that be?

"WaitingTime" is the name of the mod.

**Comment by Jordaan128** [comment] 2019-03-07 20:29
Just wanted to add that the removal of the mod did indeed fix my issue. Thanks a lot guys, sorry I didnt reply sooner been busy working. Cheers!

**Comment by KazumaHirano** [comment] 2019-03-14 03:32
Confirmed this works! Loading time went from 49 minutes to around 5 minutes

**Comment by magnusjjj** [comment] 2019-03-21 08:20
@Jordaan128 , can you reopen this issue? It's still an active problem to a lot of us and has not been fixed, and closing it might drop it from the todo?

Four computers now, where two of them are core i7's with beefy graphics cards. Loading time is about 24 minutes, even with upped memory. Both disks are NVME ssd's.

Loading seems to be capped to the refresh rate of the screen while loadingtime is active.
Disabling loadingtime and disabling vsync drops the loading time to about 5 minutes. 

You should perhaps add it at the very least as a 'if you have issues..' thing on twitch?

**Comment by Jordaan128** [comment] 2019-03-21 08:46
@magnusjjj no problem mate

**Closed** 2019-04-19 01:54 UTC
Labels: wontfix
