### ISSUE TITLE
Bucket Dupe

### ISSUE THREAD

**Issue by Bawakiller** [Cazadorsniper/PO3#1545] opened 2021-07-23 12:24 UTC
# Use the search function before reporting to see if the issue has been reported before.
PO3-3.3.61 (1.12.2)
Normal
Singleplayer

you can dupe buckets with only 2 buckets and a cow

get 2 buckets, milk cows ( havent tryed if it works by getting milk from other places ) , place both buckets in your hotbar and drink both of them, the first one will be normal and when you drink the second one the bucket will get duped by 1,
video : https://www.youtube.com/watch?v=rK5Q4iqKde0
no crash

**Comment by Cazadorsniper** [comment] 2021-07-23 13:46
Duplicate of #1525

**Closed by Cazadorsniper** 2021-07-23 13:46 UTC
