### ISSUE TITLE
Missing recipe from extra utils2

### ISSUE THREAD

**Issue by VoidedOut** [Cazadorsniper/PO3#1058] opened 2020-05-03 00:57 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.55
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
single
**Description:**
No recipe for item filters from extra utils in JEI. Not sure if they are still craftable because I do not know the recipe
**Steps to reproduce:**
Look up item filter from extra utils 2 and try to see the recipe

**Comment by Cazadorsniper** [comment] 2020-05-03 01:00
They are disabled.

**Comment by Cazadorsniper** [comment] 2020-05-03 01:01
Duplicate of #996

**Closed by Cazadorsniper** 2020-05-03 01:01 UTC
