### ISSUE TITLE
crash randomly after world is loaded

### ISSUE THREAD

**Issue by 73Salmin** [Cazadorsniper/PO3#541] opened 2019-08-05 08:57 UTC
Pack Version:
3.0.41

Singleplayer, Multiplayer, or LAN?:
Singleplayer

Description:
when i started playing the game everything was just fine and then after i started in abyssalcraft mod my game crashed every 5-7 min into the world.

Steps to reproduce:
even if i afk the game crashes

Crash log (use pastebin or issue will be closed):
https://pastebin.com/XTQLrpD3

**Comment by Cazadorsniper** [comment] 2019-08-05 13:04
Duplicate of #469

**Closed by Cazadorsniper** 2019-08-05 13:04 UTC
