### ISSUE TITLE
transfer pipes and nodes

### ISSUE THREAD

**Issue by maniever** [Cazadorsniper/PO3#980] opened 2020-04-03 16:58 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:**all
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:**they were craftable in older versions I think one month ago why is it not craftable now

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment] 2020-04-03 17:03
Duplicate of #979

**Closed by Cazadorsniper** 2020-04-03 17:03 UTC
Labels: duplicate, wontfix
