### ISSUE TITLE
Crafting recipe bugs

### ISSUE THREAD

**Issue by Dessuu** [Cazadorsniper/PO3#1253] opened 2020-06-10 12:07 UTC
I just opened new server to start play and this is what happened, it does not actually give diamonds but i cant even craft furnace..
[Screenshot1](https://i.imgur.com/Rbd7CrX.png)
[Screenshot2](https://i.imgur.com/YGJb9j5.png)
[Part of latest.log](https://pastebin.com/EeaCCjeG)

**Comment by sklirg** [comment] 2020-06-17 22:37
@Cazadorsniper , is Screenshot2 in the above post also a duplicate of #1250 ?

**Description:**

I've started experiencing this problem since upgrading my server (and clients) from PO3-3.3.58A to PO3-3.3.59.

It worked fine on v3.3.58A.

Recipes I've found to not produce the expecting item:
**3x Iron Plate -> Iron Bucket**
Recipe in NEI
![image](https://user-images.githubusercontent.com/5422571/84956887-5a35a880-b0fa-11ea-9dbb-6611f754c811.png)
Crafting station
![image](https://user-images.githubusercontent.com/5422571/84956906-6588d400-b0fa-11ea-99b4-be3e7ec9d0f3.png)
Crafting station attempt 2
![image](https://user-images.githubusercontent.com/5422571/84956917-6de10f00-b0fa-11ea-94a3-68dde49d8112.png)

**Workbench**
Recipe in NEI (says lapis works, and automatically pulls lapis into crafting station)
![image](https://user-images.githubusercontent.com/5422571/84956577-cfed4480-b0f9-11ea-8acf-bf65ea4e0e88.png)
Crafting station
![image](https://user-images.githubusercontent.com/5422571/84956596-d7ace900-b0f9-11ea-9951-38e7a683adde.png)

I can not see the same issue as in Screenshot1 above:
![image](https://user-images.githubusercontent.com/5422571/84957623-e4324100-b0fb-11ea-869f-03781fc63825.png)


I'm not sure if this is related, but I started getting errors like these in the chat when logging in after the upgrade:
Scrolled to top
![image](https://user-images.githubusercontent.com/5422571/84957064-b8628b80-b0fa-11ea-9e2c-4718d93d3ee3.png)
Scrolled to bottom
![image](https://user-images.githubusercontent.com/5422571/84957045-ad0f6000-b0fa-11ea-9190-8a30ebf21a0b.png)

**Steps to reproduce:**

See images in description.

**Pack Version: Pack Mode (Normal, Titan, Kappa): Singleplayer, Multiplayer, or LAN?:**

PO3-3.3.59, normal mode, multiplayer


**Crash log (use pastebin or issue will be closed):**

I cannot see anything relevant in the logs while I put the items in the crafting table, but I can upload the full logs if you wish to dig deeper.

If you need more info, give me a shout and I'll do what I can.

**Comment by Cazadorsniper** [comment] 2020-06-18 00:13
replace the scripts folder

**Closed** 2020-08-06 23:29 UTC
Labels: Issue template Missing
