### ISSUE TITLE
Lunar Singularity Recipe Problem

### ISSUE THREAD

**Issue by reaperstech** [Cazadorsniper/PO3#934] opened 2020-03-23 17:02 UTC
# Use the search function before reporting to see if the issue has been reported before. 
Issue is [filed](https://github.com/Cazadorsniper/PO3/issues/931) but with improper formatting so filing this as the other is likely to be closed. Hoping this doesn't get closed as a duplicate but we'll see.

**Pack Version:** 3.2.54
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** SP and MP

**Description:** Lunar Singularity recipe was changed to use blocks but produces Dummy Singularities and not Lunar.
Recipe:
![2020-03-23_12 54 27](https://user-images.githubusercontent.com/62254861/77342123-194e1380-6d06-11ea-8250-ff00c6b17578.png)

Result:
![2020-03-23_12 53 47](https://user-images.githubusercontent.com/62254861/77342172-2d921080-6d06-11ea-8ebb-db20dd90f571.png)
![2020-03-23_12 53 51](https://user-images.githubusercontent.com/62254861/77342176-2e2aa700-6d06-11ea-99bc-f58ec87b3a8d.png)

**Steps to reproduce:** Put 9001 Lunar blocks into a quantum compressor.

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by Cazadorsniper** [comment] 2020-03-23 17:48
Duplicate of #931

**Closed by Cazadorsniper** 2020-03-23 17:48 UTC
