### ISSUE TITLE
Extra Utilities Trouble

### ISSUE THREAD

**Issue by Gehenna0** [Cazadorsniper/PO3#1054] opened 2020-05-02 18:55 UTC
The Extra Utilities Mod is not working correctly. Items like transfer pipes & nodes are not present. I noticed the problem today, reinstalled the individual mod to no effect, eventually removing the mod pack completely to also no effect. I use twitch to for this modpack. When I click on the mods list inside Minecraft, Extra Utilities is present, but the disable and configure buttons are grayed out and have no interaction. Any assistance appreciated.

**Comment by Cazadorsniper** [comment] 2020-05-02 19:04
Duplicate of #996

**Closed by Cazadorsniper** 2020-05-02 19:04 UTC
