### ISSUE TITLE
Uncraftable items in Single player

### ISSUE THREAD

**Issue by TimothyCase** [Cazadorsniper/PO3#1458] opened 2020-12-30 04:02 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.61
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
There are missing recipes. The item shows in JEI, but there is no recipe. Manually doing the correct recipe produces no output.
Extra Utilities 2
    Filter
    Filter Fluids
The Twilight Forest
    Uncrafting Table
**Steps to reproduce:**
Look up the item in JEI and attempt to look at the recipe.
Using a default crafting table manually fill in the recipe.
![2020-12-29_21 42 38](https://user-images.githubusercontent.com/76762329/103329192-4d86fb00-4a21-11eb-92f5-2e3581cb1ae2.png)
![2020-12-29_21 42 44](https://user-images.githubusercontent.com/76762329/103329194-4e1f9180-4a21-11eb-91e5-26ac5db53eb9.png)
![2020-12-29_21 42 53](https://user-images.githubusercontent.com/76762329/103329195-4eb82800-4a21-11eb-86da-ad7644a01870.png)
**Crash log (use pastebin or issue will be closed):**
N/A

**Comment by Cazadorsniper** [comment] 2020-12-30 13:50
Duplicate of #1457

**Closed by Cazadorsniper** 2020-12-30 13:50 UTC
