### ISSUE TITLE
Duplication Bug: with Better Furnace and Pulverizer

### ISSUE THREAD

**Issue by ZurexX** [Cazadorsniper/PO3#1130] opened 2020-05-10 20:19 UTC
**Pack Version:*3.2.55*
**Pack Mode (Normal, Titan, Kappa):*Titan*
**Singleplayer, Multiplayer, or LAN?:*Multiplayer*

**Description:*Duplication Bug with Processing Upgrade (Better Furnace) and Pulverizer*

**Steps to reproduce:*Pulverize any Ingot like Iron Ingot = Iron dust and throw it in the Zenith Furnace with the Processing Upgrade = Then you get 2 Ingot*

 This is a Question of me: Is it a Bug or a Feature?

**Comment by random53** [comment] 2020-05-10 22:29
90% sure its a feature the recipe is very late game in kappa so i doubt its an oversight

**Comment by random53** [comment] 2020-05-10 22:31
Yeah it's already been posted twice and closed by caz both times

**Comment by ZurexX** [comment] 2020-05-10 22:38
But in Titan mode you can dupe Ingots in early game

**Comment by MrFieryPotato** [comment] 2020-05-11 01:16
its intended i think. im pretty sure thats also why patient bags are diamond blocks instead of a nether star

**Comment by ZurexX** [comment] 2020-05-11 15:27
> its intended i think. im pretty sure thats also why patient bags are diamond blocks instead of a nether star

So it is intended to get unlimited Resources in early game ?

**Comment by Cazadorsniper** [comment] 2020-05-11 19:25
Processing upgrade is doing exactly as intended.

**Closed by Cazadorsniper** 2020-05-11 19:25 UTC
