### ISSUE TITLE
Transfer Node and Pipes missing

### ISSUE THREAD

**Issue by ziad10a** [Cazadorsniper/PO3#1043] opened 2020-04-29 14:01 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
1.12.2

**Pack Mode (Normal, Titan, Kappa):**
Normal

**Gamemode:**
Singleplayer

**Description:**
I can't seem to be able to build the transfer pipe and nodes, are they missing ?

**Steps to reproduce:**
Using JEI

**Crash log (use pastebin or issue will be closed):**

**Comment by ziad10a** [comment] 2020-04-30 12:21
Hey @Cazadorsniper 
Can you please put the link for the duplicate issue?
I'd really appreciate it

**Comment by Cazadorsniper** [comment] 2020-04-30 14:26
Duplicate of #996

**Closed by Cazadorsniper** 2020-04-30 14:26 UTC
Labels: duplicate
