### ISSUE TITLE
Problem with extra utilities 2

### ISSUE THREAD

**Issue by Rational00** [Cazadorsniper/PO3#998] opened 2020-04-10 17:41 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:** normal
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:**
Just started the modpack and am somewhat new to the modding community so I've been watching YouTube videos on PO3, and I see a lot of youtubers use extra utilities pipes/nodes early game. So I thought I would do the same but when I searched anything EU2 related in the search bar in the modpack nothing showed up but the EU2 book. I went into the mod list and shows its available but there's nothing in the pack with EU2 in it.

any help would be appreciated 
thanks

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment] 2020-04-10 18:26
Duplicate of #996

**Closed by Cazadorsniper** 2020-04-10 18:26 UTC
Labels: duplicate
