### ISSUE TITLE
Crash on loading. 

### ISSUE THREAD

**Issue by ExAlePloit** [Cazadorsniper/PO3#1710] opened 2022-11-07 19:49 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.4.10**
**Description:Always the same error on loading screen. I re-downloaded the modpack but is not fixing the issue.**

**Crash log : https://pastebin.com/SgzLTVkp**

**Comment by RanonG** [comment] 2022-11-07 22:04
Same issue here. the modpack was working this morning and suddenly I'm getting this crash report

**Comment by BrobearGaming** [comment] 2022-11-07 22:43
exact same problem also. setting B:"Enable Galaxy Space Compatibility"=true in the config file doesnt help and using the support document to find the station to disable doesnt work as the config file doesn't have the same format. obviously because its been updated

**Comment by ExAlePloit** [comment] 2022-11-07 23:00
all my friends have the same error (5 people)

**Comment by Cazadorsniper** [comment] 2022-11-08 12:49
Duplicate of #1709

**Closed as completed by Cazadorsniper** 2022-11-08 12:49 UTC
