### ISSUE TITLE
Duplicating Dank Null

### ISSUE THREAD

**Issue by hendolad1234** [Cazadorsniper/PO3#1124] opened 2020-05-09 18:49 UTC
**Pack Version:3.3.57**
**Pack Mode (Normal, Titan, Kappa):kappa**
**Singleplayer, Multiplayer, or LAN?:Singleplayer**

**Description:Trying to store a dank null in the docking station opens the dank nulls storage and after repeated attempts at putting it in the docking station the dank null duplicates itself, one in the main hand and one in the off hand, i did have a power cut a few hours earlier and my dank null did seem to be missing, so maybe the docking station got bugged im not sure i did break and replace it but it still ended up duplicating the dank null**

**Steps to reproduce:try to store a diamond dank null in the docking station, the docking station in my case is on top of a Immersive Storage crate im not sure if this is the issue **

**Crash log (use pastebin or issue will be closed):**

**Comment by hendolad1234** [comment] 2020-05-09 18:50
https://pastebin.com/x5PqnwxJ i do have a log not sure if its needed or not but either way

**Comment by hendolad1234** [comment] 2020-05-09 19:34
https://medal.tv/clips/23961776/d13379NnhJbN here is a clip of the dupe working, it only works if the dank null is empty

**Comment by NajtDev** [comment] 2020-05-11 10:25
Replication :
Only happens with newly crafted empty dank/null
1. Right-click with dank/null on the docking station
2. Shift-Right click with dank/null on the docking station
A duplicate of the dank/null shows up in the offhand slot

It might be related to the mod itself. But I don't have time to test the mod separately.

**Closed** 2020-05-15 02:13 UTC
Labels: Fixed For Next Update
