### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by PexonTV** [Cazadorsniper/PO3#530] opened 2019-07-31 20:04 UTC
Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.0.41
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Game crashes after a few seconds ingame

Steps to reproduce: 16 Spectrecoils in Simple Void

Crash log (use pastebin or issue will be closed):
https://pastebin.com/wqSLgVRj

**Comment by Cazadorsniper** [comment] 2019-07-31 20:12
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-31 20:12 UTC
