### ISSUE TITLE
Neutral steel of the fifth degree consumes the wrong amount of input materials

### ISSUE THREAD

**Issue by numbertheo** [Cazadorsniper/PO3#1216] opened 2020-05-28 10:17 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.58A
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
The recipe for neutral steel of the fifth degree does not process according to what is shown in NEI.
One to five inputs are consumed from every slot producing the same output.

**Steps to reproduce:**
- Place one neutral steel of the fourth degree into each slot of the alloy smelter
  - one neutral steel of the  fourth degree is consumed from each slot producing one neutral steel of the fifth degree
- Place a stack of neutral steel of the fourth degree into each slot of the alloy smelter
    - five neutral steel of the  fourth degree are consumed from each slot producing one neutral steel of the fifth degree

**Crash log (use pastebin or issue will be closed):**

**Comment by Caedis** [comment] 2020-05-28 12:23
Duplicate of #1200

**Comment by numbertheo** [comment] 2020-05-28 23:49
https://github.com/Cazadorsniper/PO3/issues/1200 is about the recipe not matching the rest of the neutral steel chain.  This is about the recipe not functioning correctly in the alloy smelter. It looks like the issues come from the same source but that issue does not mention the recipe not functioning as intended.

**Closed** 2020-05-29 00:55 UTC
Labels: Fixed For Next Update
