### ISSUE TITLE
EnderEvolution Enderman Crash when killed by Mob Masher

### ISSUE THREAD

**Issue by TiedierColt** [Cazadorsniper/PO3#498] opened 2019-07-17 04:50 UTC
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
_**"A quick fix for this is to set the "Probability to spawn" to zero in the EnderEvolution.cfg and the mobs will stop spawning." **_ doesn't work.

**Steps to reproduce:**
Have an Evolved Enderman die to the Mob Masher

**Crash log (use pastebin or issue will be closed):**
[crash-2019-07-17_00.12.51-server.txt](https://github.com/Cazadorsniper/PO3/files/3400201/crash-2019-07-17_00.12.51-server.txt)
[crash-2019-07-17_00.29.18-server.txt](https://github.com/Cazadorsniper/PO3/files/3400202/crash-2019-07-17_00.29.18-server.txt)
[crash-2019-07-17_00.43.43-server.txt](https://github.com/Cazadorsniper/PO3/files/3400203/crash-2019-07-17_00.43.43-server.txt)

**Comment by Cazadorsniper** [comment] 2019-07-17 14:20
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-17 14:20 UTC
Labels: duplicate
