### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Cazitron** [Cazadorsniper/PO3#28] opened 2019-02-27 02:13 UTC
**Pack Version:**       3.0.38

**Description:**     I "shift-double-clicked" a full "slightly larger chest" of acceleration cards and it crashed my game, let me know if this happens for you or if its something on my side, because this has happened for me on the modpack "Stoneblock when "shift-clicking" stacks of infinity blocks outside of a golden bag of holding.

**Steps to reproduce:** In previous statement ^^^^^

**Crash log:**   I have no clue how to find the crash report with the new launcher.

**Comment by Cazadorsniper** [comment] 2019-02-27 04:49
This is a duplicate of several reports, update extrautils then then try that again.

**Comment by Cazitron** [comment] 2019-02-27 21:34
Caz then wont work, we're on a server that would telling everyone on our server and practically teaching them how to update a singular mod in a mod-pack so they can still play

**Comment by Cazitron** [comment] 2019-02-27 21:53
> This is a duplicate of several reports, update extrautils then then try that again.

Caz that wont work, we're on a server of 3-5 people, and only one other, other than myself, is an experienced mod-pack player, so that would mean telling everyone on our server and practically teaching them how to update a singular mod in a mod-pack so that they can still play. Which also means that we have to remember to tell any one new that as well

**Comment by Cazadorsniper** [comment] 2019-02-28 17:46
Then wait for a new pack update.

**Closed by Cazadorsniper** 2019-02-28 17:46 UTC
Labels: duplicate
