### ISSUE TITLE
Bucket Dupe

### ISSUE THREAD

**Issue by elgrimbahola** [Cazadorsniper/PO3#911] opened 2020-03-17 14:20 UTC
**Pack Version:**
3.2.52

**Pack Mode:**
Kappa Mode

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
When drinking milk from a bucket, you get back 2 buckets instead of one.

**Steps to reproduce:**
Must have 2 buckets in the action slot bar (different slots).
Step 1. Get 1 bucket of milk from cow.
Step 2. Place 1 empty bucket on action bar, and milk on another slot.
Step 3. Drink milk bucket and both slots will gain 1 empty bucket, effectively duping the bucket.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment] 2020-03-17 18:38
Duplicate of #873

**Closed by Cazadorsniper** 2020-03-17 18:38 UTC
Labels: duplicate
