### ISSUE TITLE
Evlolved Emdermand and MobUtilities Iron Spikes Crash

### ISSUE THREAD

**Issue by wmcmillenjr** [Cazadorsniper/PO3#525] opened 2019-07-30 01:39 UTC
**Pack Version:**
3.0.14
**Singleplayer, Multiplayer, or LAN?:**
Single Player world
**Description:**
An Evolved Enderman being killed with the MobUtilities Iron Spikes crashes game. 
**Steps to reproduce:**
Place Mob Utilities Iron spikes in a mob farm and let an Evolved Enderman die on them. 
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/r1LgHgkK

**Comment by Cazadorsniper** [comment] 2019-07-30 01:40
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-30 01:40 UTC
