### ISSUE TITLE
Does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

### ISSUE THREAD

**Issue by cmousoula** [Cazadorsniper/PO3#513] opened 2019-07-23 21:25 UTC
Very often by running around the map or teleporting the game crashes out. Please see below error logs:

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

------------------

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RandomPatches (randompatches-1.12.2-1.17.1.0.jar)
  LibLoader (# LibLoader.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  MekanismCoremod (Mekanism-1.12.2-9.7.8.379.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  WTPlugin (WaitingTime-1.0.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  Quark Plugin (Quark-r1.5-167.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/23/19 10:08 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at lumien.randomthings.tileentity.TileEntitySpectreCoil.hasCapability(TileEntitySpectreCoil.java:65)
	at p455w0rdslib.capabilities.CapabilityLightEmitter.hasCap(CapabilityLightEmitter.java:47)
	at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:152)
	at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
	at net.minecraft.client.renderer.RenderGlobal.func_174982_a(RenderGlobal.java:1133)
	at net.minecraft.client.renderer.RenderGlobal.func_174977_a(RenderGlobal.java:1125)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1328)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Cazadorsniper** [comment] 2019-07-24 03:07
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-24 03:07 UTC
