### ISSUE TITLE
Random Crashes in Sigleplayer 

### ISSUE THREAD

**Issue by Phil204** [Cazadorsniper/PO3#548] opened 2019-08-11 14:27 UTC
**Pack Version:**
3.0.41

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
Out of nowhere when I'm doing something my game just freezes and then it starts saying game not responding then it crashes. 

**Steps to reproduce:**
Im not sure what this means. It just happens like every 20 mins

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/iszdD5t6

**Comment by Cazadorsniper** [comment] 2019-08-11 14:46
Duplicate of #469

**Closed by Cazadorsniper** 2019-08-11 14:46 UTC
