### ISSUE TITLE
Server Crashing,Evolved Enderman

### ISSUE THREAD

**Issue by Amorean** [Cazadorsniper/PO3#540] opened 2019-08-04 22:41 UTC
I am hosting a private dedicated server for some friends. We do not build together, but thing have gone well for the most part. One group place down a Mob Grinder in a dark room to build up essence and it caused the Server to crash. Below is log with crash details. This might be related to known issue, but I am not sure. If so I apologize for the duplicate issue.

What is the plan of action to resolve this issue?

Paste Bin: https://pastebin.com/DLhuh3hx

**Comment by Amorean** [comment] 2019-08-04 22:47
I used a Server Backup to get my server back up, and made it clear to have them avoid using Mod Grinders for now.

**Comment by Amorean** [comment] 2019-08-04 22:52
Seems to be related more to the Evolved Enderman, not so much the Mob Grinders, going to test by disabling the Evolved Enderman.

**Comment by Cazadorsniper** [comment] 2019-08-05 01:01
Duplicate of #469

**Closed by Cazadorsniper** 2019-08-05 01:01 UTC
