### ISSUE TITLE
Mob grinder crashing server

### ISSUE THREAD

**Issue by Sebfrede** [Cazadorsniper/PO3#502] opened 2019-07-19 18:49 UTC
I am getting a server crash when using the mob grinder from mob_grinding_utils. Something about a block entity tick.

I have attached my crash file from the server in the pastebin:
https://pastebin.com/L8vayWeM

**Comment by Cazadorsniper** [comment] 2019-07-19 19:48
Duplicate of #469

**Closed by Cazadorsniper** 2019-07-19 19:48 UTC
